### ISSUE TITLE
引入oauth2 jar包后 tx_lcn会与zipkin冲突

### ISSUE THREAD

**Issue by ngcly** [codeyung/hex-springcloud#1]
大佬，是不是引入oauth2 jar包后就报错了，跟tx_lcn的有冲突。而且报的错误是：
```
Field existingConcurrencyStrategy in org.springframework.cloud.netflix.hystrix.security.HystrixSecurityAutoConfiguration required a single bean, but 2 were found:
	- tracingHystrixConcurrencyStrategy: defined in URL [jar:file:/C:/Users/chenning/.gradle/caches/modules-2/files-2.1/com.codingapi.txlcn/txlcn-tracing/5.0.2.RELEASE/e4d1a9fc988d78dd98c9a616270272829b37871b/txlcn-tracing-5.0.2.RELEASE.jar!/com/codingapi/txlcn/tracing/http/TracingHystrixConcurrencyStrategy.class]
	- sleuthHystrixConcurrencyStrategy: defined by method 'sleuthHystrixConcurrencyStrategy' in class path resource [org/springframework/cloud/sleuth/instrument/hystrix/SleuthHystrixAutoConfiguration.class]

```
报的跟zipkin冲突，但却是在引入oauth2 jar包后才报错，莫名其妙。

**Comment by codeyung** [comment]
tracingHystrixConcurrencyStrategy
sleuthHystrixConcurrencyStrategy
注入了相同的bean
使用@Qualifier指定注入bean试一下

**Comment by codeyung** [comment]
> 大佬，是不是引入oauth2 jar包后就报错了，跟tx_lcn的有冲突。而且报的错误是：
> 
> ```
> Field existingConcurrencyStrategy in org.springframework.cloud.netflix.hystrix.security.HystrixSecurityAutoConfiguration required a single bean, but 2 were found:
> 	- tracingHystrixConcurrencyStrategy: defined in URL [jar:file:/C:/Users/chenning/.gradle/caches/modules-2/files-2.1/com.codingapi.txlcn/txlcn-tracing/5.0.2.RELEASE/e4d1a9fc988d78dd98c9a616270272829b37871b/txlcn-tracing-5.0.2.RELEASE.jar!/com/codingapi/txlcn/tracing/http/TracingHystrixConcurrencyStrategy.class]
> 	- sleuthHystrixConcurrencyStrategy: defined by method 'sleuthHystrixConcurrencyStrategy' in class path resource [org/springframework/cloud/sleuth/instrument/hystrix/SleuthHystrixAutoConfiguration.class]
> ```
> 
> 报的跟zipkin冲突，但却是在引入oauth2 jar包后才报错，莫名其妙。

不好意思我最近很忙  没有回复你，这两个bean用了一个注解 加载的时候找到了两个
oauth2.0 没有整合 是因为自己这边没有对于统一权限鉴权想到一些好的方法 还有oauth2.0的场景

**Comment by codeyung** [comment]
还可以在tx-lcn里提一下issue 这边也有提问的 
https://github.com/codingapi/tx-lcn/issues/437

**Comment by codeyung** [comment]
> 大佬，是不是引入oauth2 jar包后就报错了，跟tx_lcn的有冲突。而且报的错误是：
> 
> ```
> Field existingConcurrencyStrategy in org.springframework.cloud.netflix.hystrix.security.HystrixSecurityAutoConfiguration required a single bean, but 2 were found:
> 	- tracingHystrixConcurrencyStrategy: defined in URL [jar:file:/C:/Users/chenning/.gradle/caches/modules-2/files-2.1/com.codingapi.txlcn/txlcn-tracing/5.0.2.RELEASE/e4d1a9fc988d78dd98c9a616270272829b37871b/txlcn-tracing-5.0.2.RELEASE.jar!/com/codingapi/txlcn/tracing/http/TracingHystrixConcurrencyStrategy.class]
> 	- sleuthHystrixConcurrencyStrategy: defined by method 'sleuthHystrixConcurrencyStrategy' in class path resource [org/springframework/cloud/sleuth/instrument/hystrix/SleuthHystrixAutoConfiguration.class]
> ```
> 
> 报的跟zipkin冲突，但却是在引入oauth2 jar包后才报错，莫名其妙。

不好意思我最近很忙 没有回复你，
tracingHystrixConcurrencyStrategy
sleuthHystrixConcurrencyStrategy
注入了相同的bean
使用@qualifier指定注入bean试一下
oauth2.0 没有整合 是因为自己这边没有对于统一权限鉴权想到一些好的方法 还有oauth2.0的场景
还可以在tx-lcn里提一下issue 这边也有提问的
codingapi/tx-lcn#437
真正需要支持分布式事务的话 需要经过比较严谨的验证，要有确实的可用性  我这个只是找了个接入相对方便我本地做测试 搭建这个demo 的分布式事务管理 ，用到生产上还是要三思

**Comment by ngcly** [comment]
我也想用@qualifier指定，但这些注入都是框架自动的，你都没地方去指定，除非去改源码。lcn我也是自己搭着玩的，才发现bug一堆 而且半年都没人维护了。算了，换其他框架了、谢谢大佬回复。
